export interface QuizQuestion {
  id: string;
  category: string;
  question: string;
  answer: string;
  images: string[];
  hint?: string;
}

export const quizData: QuizQuestion[] = [
  // Body Planes
  {
    id: "plane-1",
    category: "Body Planes",
    question: "This plane divides the body into left and right halves: _______",
    answer: "sagittal",
    images: ["/images/v76IFwxfiI6V.jpg", "/images/YS4fBzwQII73.jpg"],
    hint: "Divides the body down the middle.",
  },
  {
    id: "plane-2",
    category: "Body Planes",
    question: "This plane divides the body into front and back: _______",
    answer: "frontal",
    images: ["/images/v76IFwxfiI6V.jpg", "/images/e6cDkMQoYhHn.webp"],
    hint: "Also called coronal plane.",
  },
  {
    id: "plane-3",
    category: "Body Planes",
    question: "This plane divides the body into upper and lower sections: _______",
    answer: "transverse",
    images: ["/images/v76IFwxfiI6V.jpg", "/images/pWtSr7d2Ivwv.png"],
    hint: "Also called horizontal plane.",
  },
  {
    id: "plane-4",
    category: "Body Planes",
    question: "The _______ plane runs exactly down the middle of the body.",
    answer: "median",
    images: ["/images/v76IFwxfiI6V.jpg"],
    hint: "Also called midsagittal plane.",
  },
  {
    id: "plane-5",
    category: "Body Planes",
    question: "A _______ plane is a sagittal plane that does not run exactly down the middle.",
    answer: "parasagittal",
    images: ["/images/v76IFwxfiI6V.jpg"],
    hint: "Para means beside.",
  },

  // Directional Terms
  {
    id: "dir-1",
    category: "Directional Terms",
    question: "The direction toward the head or upper part of the body: _______",
    answer: "superior",
    images: ["/images/pWtSr7d2Ivwv.png", "/images/aNkdMIvL92Ts.png"],
    hint: "Opposite of inferior.",
  },
  {
    id: "dir-2",
    category: "Directional Terms",
    question: "The direction toward the feet or lower part of the body: _______",
    answer: "inferior",
    images: ["/images/pWtSr7d2Ivwv.png", "/images/aNkdMIvL92Ts.png"],
    hint: "Opposite of superior.",
  },
  {
    id: "dir-3",
    category: "Directional Terms",
    question: "The direction toward the front of the body: _______",
    answer: "anterior",
    images: ["/images/pWtSr7d2Ivwv.png", "/images/uviIm0OGY09G.jpg"],
    hint: "Facing forward.",
  },
  {
    id: "dir-4",
    category: "Directional Terms",
    question: "The direction toward the back of the body: _______",
    answer: "posterior",
    images: ["/images/pWtSr7d2Ivwv.png", "/images/uviIm0OGY09G.jpg"],
    hint: "Opposite of anterior.",
  },
  {
    id: "dir-5",
    category: "Directional Terms",
    question: "The direction toward the midline of the body: _______",
    answer: "medial",
    images: ["/images/aNkdMIvL92Ts.png"],
    hint: "Moving toward the middle.",
  },
  {
    id: "dir-6",
    category: "Directional Terms",
    question: "The direction away from the midline of the body: _______",
    answer: "lateral",
    images: ["/images/aNkdMIvL92Ts.png"],
    hint: "Opposite of medial.",
  },
  {
    id: "dir-7",
    category: "Directional Terms",
    question: "The direction toward the head (synonym for superior): _______",
    answer: "cephalic",
    images: ["/images/pWtSr7d2Ivwv.png"],
    hint: "Cephal- refers to head.",
  },
  {
    id: "dir-8",
    category: "Directional Terms",
    question: "The direction toward the tail or lower end (synonym for inferior): _______",
    answer: "caudal",
    images: ["/images/pWtSr7d2Ivwv.png"],
    hint: "Caud- refers to tail.",
  },
  {
    id: "dir-9",
    category: "Directional Terms",
    question: "The direction toward the back, especially for brain and spinal cord: _______",
    answer: "dorsal",
    images: ["/images/pWtSr7d2Ivwv.png"],
    hint: "Refers to back side.",
  },
  {
    id: "dir-10",
    category: "Directional Terms",
    question: "The direction toward the front or belly side: _______",
    answer: "ventral",
    images: ["/images/pWtSr7d2Ivwv.png"],
    hint: "Refers to belly/front.",
  },
  {
    id: "dir-11",
    category: "Directional Terms",
    question: "On the same side of the body: _______",
    answer: "ipsilateral",
    images: ["/images/aNkdMIvL92Ts.png"],
    hint: "Ipsi- means same.",
  },
  {
    id: "dir-12",
    category: "Directional Terms",
    question: "On the opposite side of the body: _______",
    answer: "contralateral",
    images: ["/images/aNkdMIvL92Ts.png"],
    hint: "Contra- means opposite.",
  },
  {
    id: "dir-13",
    category: "Directional Terms",
    question: "Closer to the point of attachment or origin: _______",
    answer: "proximal",
    images: ["/images/uviIm0OGY09G.jpg"],
    hint: "Closer to center.",
  },
  {
    id: "dir-14",
    category: "Directional Terms",
    question: "Farther from the point of attachment or origin: _______",
    answer: "distal",
    images: ["/images/uviIm0OGY09G.jpg"],
    hint: "Farther away.",
  },
  {
    id: "dir-15",
    category: "Directional Terms",
    question: "At or near the surface of the body: _______",
    answer: "superficial",
    images: ["/images/1GM4TnEadyti.png"],
    hint: "Close to surface.",
  },
  {
    id: "dir-16",
    category: "Directional Terms",
    question: "Away from the surface, toward the interior: _______",
    answer: "deep",
    images: ["/images/1GM4TnEadyti.png"],
    hint: "Opposite of superficial.",
  },

  // Organ Systems
  {
    id: "sys-1",
    category: "Organ Systems",
    question: "The system that covers and protects the body; includes skin: _______",
    answer: "integumentary",
    images: ["/images/1GM4TnEadyti.png", "/images/ZkoYvKgRy7Zf.jpeg"],
    hint: "Integument means covering.",
  },
  {
    id: "sys-2",
    category: "Organ Systems",
    question: "The system that provides support and structure; includes bones and cartilage: _______",
    answer: "skeletal",
    images: ["/images/k4OWdcLn2tEY.jpg"],
    hint: "Framework of body.",
  },
  {
    id: "sys-3",
    category: "Organ Systems",
    question: "The system that enables movement; includes skeletal muscles: _______",
    answer: "muscular",
    images: ["/images/TEPACMSjKVgn.jpg", "/images/YSaeF2dg1954.jpg"],
    hint: "Muscles contract.",
  },
  {
    id: "sys-4",
    category: "Organ Systems",
    question: "The system that controls body functions; includes brain and spinal cord: _______",
    answer: "nervous",
    images: ["/images/pWtSr7d2Ivwv.png"],
    hint: "Nerves transmit signals.",
  },
  {
    id: "sys-5",
    category: "Organ Systems",
    question: "The system that regulates body functions through hormones; includes pituitary and thyroid glands: _______",
    answer: "endocrine",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Glands secrete hormones.",
  },
  {
    id: "sys-6",
    category: "Organ Systems",
    question: "The system that transports blood and nutrients; includes heart and blood vessels: _______",
    answer: "circulatory",
    images: ["/images/vQPAx2dC7uBq.png", "/images/RPdKyKa2MvtT.png"],
    hint: "Heart pumps blood.",
  },
  {
    id: "sys-7",
    category: "Organ Systems",
    question: "The system that defends against pathogens; includes lymph nodes and spleen: _______",
    answer: "lymphatic",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Lymph fights infection.",
  },
  {
    id: "sys-8",
    category: "Organ Systems",
    question: "The system that exchanges gases; includes lungs and trachea: _______",
    answer: "respiratory",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Breathing system.",
  },
  {
    id: "sys-9",
    category: "Organ Systems",
    question: "The system that breaks down food; includes stomach and intestines: _______",
    answer: "digestive",
    images: ["/images/vQPAx2dC7uBq.png", "/images/RPdKyKa2MvtT.png"],
    hint: "Digestion breaks down food.",
  },
  {
    id: "sys-10",
    category: "Organ Systems",
    question: "The system that removes waste; includes kidneys and bladder: _______",
    answer: "urinary",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Produces and eliminates urine.",
  },
  {
    id: "sys-11",
    category: "Organ Systems",
    question: "The system that produces offspring; includes testes or ovaries: _______",
    answer: "reproductive",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Creates new individuals.",
  },

  // Specific Organs - Identification Focus
  {
    id: "organ-1",
    category: "Specific Organs",
    question: "The main organ of the circulatory system that pumps blood: _______",
    answer: "heart",
    images: ["/images/vQPAx2dC7uBq.png", "/images/RPdKyKa2MvtT.png"],
    hint: "Muscular pump.",
  },
  {
    id: "organ-2",
    category: "Specific Organs",
    question: "The main organs of respiration where gas exchange occurs: _______",
    answer: "lungs",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Fill with air.",
  },
  {
    id: "organ-3",
    category: "Specific Organs",
    question: "The main organ of the digestive system where food is broken down: _______",
    answer: "stomach",
    images: ["/images/vQPAx2dC7uBq.png", "/images/RPdKyKa2MvtT.png"],
    hint: "Muscular sac.",
  },
  {
    id: "organ-4",
    category: "Specific Organs",
    question: "The main organ of the nervous system that controls all body functions: _______",
    answer: "brain",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Control center.",
  },
  {
    id: "organ-5",
    category: "Specific Organs",
    question: "A bundle of nerves that extends from the brain down the spine: _______",
    answer: "spinal cord",
    images: ["/images/pWtSr7d2Ivwv.png"],
    hint: "Protected by vertebrae.",
  },
  {
    id: "organ-6",
    category: "Specific Organs",
    question: "The largest internal organ that filters blood and produces urine: _______",
    answer: "kidneys",
    images: ["/images/vQPAx2dC7uBq.png", "/images/RPdKyKa2MvtT.png"],
    hint: "Bean-shaped organs.",
  },
  {
    id: "organ-7",
    category: "Specific Organs",
    question: "The largest gland in the body that aids in digestion: _______",
    answer: "liver",
    images: ["/images/vQPAx2dC7uBq.png", "/images/RPdKyKa2MvtT.png"],
    hint: "Reddish-brown.",
  },
  {
    id: "organ-8",
    category: "Specific Organs",
    question: "The small organ that stores bile to aid in fat digestion: _______",
    answer: "gallbladder",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Attached to liver.",
  },
  {
    id: "organ-9",
    category: "Specific Organs",
    question: "The gland that produces insulin to regulate blood sugar: _______",
    answer: "pancreas",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Endocrine and digestive organ.",
  },
  {
    id: "organ-10",
    category: "Specific Organs",
    question: "The lymphoid organ that filters blood and produces white blood cells: _______",
    answer: "spleen",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Part of lymphatic system.",
  },
  {
    id: "organ-11",
    category: "Specific Organs",
    question: "The tube that carries urine from the kidneys to the bladder: _______",
    answer: "ureter",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Paired tubes.",
  },
  {
    id: "organ-12",
    category: "Specific Organs",
    question: "The organ that stores urine until it is eliminated: _______",
    answer: "urinary bladder",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Muscular sac.",
  },
  {
    id: "organ-13",
    category: "Specific Organs",
    question: "The tube that carries urine from the bladder out of the body: _______",
    answer: "urethra",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Final part of urinary system.",
  },
  {
    id: "organ-14",
    category: "Specific Organs",
    question: "The windpipe that carries air to the lungs: _______",
    answer: "trachea",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Supported by cartilage rings.",
  },
  {
    id: "organ-15",
    category: "Specific Organs",
    question: "The voice box located in the neck: _______",
    answer: "larynx",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Produces sound.",
  },
  {
    id: "organ-16",
    category: "Specific Organs",
    question: "The throat where food and air pass through: _______",
    answer: "pharynx",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Behind the mouth.",
  },
  {
    id: "organ-17",
    category: "Specific Organs",
    question: "The tube that carries food from the mouth to the stomach: _______",
    answer: "esophagus",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Part of digestive tract.",
  },
  {
    id: "organ-18",
    category: "Specific Organs",
    question: "The part of the digestive system where most nutrient absorption occurs: _______",
    answer: "small intestine",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Long and coiled.",
  },
  {
    id: "organ-19",
    category: "Specific Organs",
    question: "The part of the digestive system where water is absorbed and feces are formed: _______",
    answer: "large intestine",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Wider than small intestine.",
  },
  {
    id: "organ-20",
    category: "Specific Organs",
    question: "The male reproductive gland that produces sperm: _______",
    answer: "testes",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Located in scrotum.",
  },
  {
    id: "organ-21",
    category: "Specific Organs",
    question: "The female reproductive gland that produces eggs: _______",
    answer: "ovaries",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Located in pelvis.",
  },
  {
    id: "organ-22",
    category: "Specific Organs",
    question: "The female reproductive organ where a fetus develops: _______",
    answer: "uterus",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Pear-shaped.",
  },
  {
    id: "organ-23",
    category: "Specific Organs",
    question: "The female reproductive canal that leads to the outside of the body: _______",
    answer: "vagina",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Birth canal.",
  },
  {
    id: "organ-24",
    category: "Specific Organs",
    question: "The male reproductive gland that produces seminal fluid: _______",
    answer: "prostate gland",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Surrounds urethra.",
  },
  {
    id: "organ-25",
    category: "Specific Organs",
    question: "The male reproductive organ that delivers sperm: _______",
    answer: "penis",
    images: ["/images/vQPAx2dC7uBq.png"],
    hint: "Contains urethra.",
  },
];

// Remove the closing bracket above and add histology questions

export const histologyQuestions: QuizQuestion[] = [
  // Histology - Epithelial Tissues
  {
    id: "histo-1",
    category: "Histology",
    question: "This epithelium appears as thin, flat cells and allows rapid diffusion; found in lungs and blood vessels: _______",
    answer: "simple squamous",
    images: ["/images/ASwW7x76KRS6.jpg", "/images/z6wBVmTu9mJG.jpg"],
    hint: "Single layer of flat cells.",
  },
  {
    id: "histo-2",
    category: "Histology",
    question: "This epithelium has multiple layers with flat cells on the surface; found in skin and mouth: _______",
    answer: "stratified squamous",
    images: ["/images/mbrXRyutvSQj.jpg", "/images/t8RvsUx0X5jV.jpg"],
    hint: "Many layers of cells.",
  },
  {
    id: "histo-3",
    category: "Histology",
    question: "This epithelium has tall, narrow cells and often contains goblet cells; found in the small intestine: _______",
    answer: "simple columnar",
    images: ["/images/vIYWUCub6zcp.jpg", "/images/DfNmUWBW6SoC.jpg"],
    hint: "Single layer of tall cells.",
  },
  {
    id: "histo-4",
    category: "Histology",
    question: "This epithelium appears stratified but all cells reach the basement membrane; found in respiratory tract: _______",
    answer: "pseudostratified columnar",
    images: ["/images/mbrXRyutvSQj.jpg"],
    hint: "Appears layered but is not.",
  },
  {
    id: "histo-5",
    category: "Histology",
    question: "This epithelium has cube-shaped cells; found in kidney tubules and glands: _______",
    answer: "simple cuboidal",
    images: ["/images/ASwW7x76KRS6.jpg"],
    hint: "Single layer of cube-shaped cells.",
  },
  // Histology - Connective Tissues
  {
    id: "histo-6",
    category: "Histology",
    question: "This cartilage is clear and glassy with fine collagen fibers; found in joints and the nose: _______",
    answer: "hyaline cartilage",
    images: ["/images/uZdhCnMuMGrx.jpg", "/images/foa1fgnki9XI.jpg"],
    hint: "Most common type of cartilage.",
  },
  {
    id: "histo-7",
    category: "Histology",
    question: "This bone tissue is dense and arranged in concentric circles around central canals: _______",
    answer: "compact bone",
    images: ["/images/FHGw2yAoQobq.jpg", "/images/v9zW0ahVTaos.jpg"],
    hint: "Dense, hard bone tissue.",
  },
  {
    id: "histo-8",
    category: "Histology",
    question: "This bone tissue has a spongy appearance with spaces filled with bone marrow: _______",
    answer: "spongy bone",
    images: ["/images/17oUOIa9OLam.jpg"],
    hint: "Appears porous and sponge-like.",
  },
  {
    id: "histo-9",
    category: "Histology",
    question: "This connective tissue is loosely organized with many blood vessels; found under skin: _______",
    answer: "areolar tissue",
    images: ["/images/ASwW7x76KRS6.jpg"],
    hint: "Loose, flexible connective tissue.",
  },
  {
    id: "histo-10",
    category: "Histology",
    question: "This connective tissue stores energy and insulates; composed of adipocytes: _______",
    answer: "adipose tissue",
    images: ["/images/ASwW7x76KRS6.jpg"],
    hint: "Fat tissue.",
  },
  // Histology - Muscle Tissues
  {
    id: "histo-11",
    category: "Histology",
    question: "This muscle tissue is striated, voluntary, and has multiple nuclei per cell: _______",
    answer: "skeletal muscle",
    images: ["/images/I5NGJialzXZV.jpg"],
    hint: "Attached to bones.",
  },
  {
    id: "histo-12",
    category: "Histology",
    question: "This muscle tissue is striated, involuntary, and found only in the heart: _______",
    answer: "cardiac muscle",
    images: ["/images/JoE6E6FqMmzh.jpg"],
    hint: "Heart muscle.",
  },
  {
    id: "histo-13",
    category: "Histology",
    question: "This muscle tissue is non-striated, involuntary, and found in blood vessel walls: _______",
    answer: "smooth muscle",
    images: ["/images/I5NGJialzXZV.jpg", "/images/JoE6E6FqMmzh.jpg"],
    hint: "No striations, spindle-shaped cells.",
  },
  // Histology - Nervous Tissue
  {
    id: "histo-14",
    category: "Histology",
    question: "The cell type in nervous tissue that conducts electrical signals with a cell body, dendrites, and axon: _______",
    answer: "neuron",
    images: ["/images/ASwW7x76KRS6.jpg"],
    hint: "Nerve cell.",
  },
  {
    id: "histo-15",
    category: "Histology",
    question: "The supporting cells in nervous tissue that protect and assist neurons: _______",
    answer: "neuroglia",
    images: ["/images/ASwW7x76KRS6.jpg"],
    hint: "Glial cells.",
  },
];

export const allQuizData = [...quizData, ...histologyQuestions];
